### PR TITLE
CI Ready

### PR DESCRIPTION
**Pull request by claudiow**
It only runs mvn clean install and proves that the build is not broken. I think that this should be the default build to track tha nothing is broken.

1. Creating a deploy build will take time. Todo:
2. Update project to org.dblock
3. Modify poms to sign jars with PGP
4. Modify and test appveyor.yml to download and install WinPGP for jar signing.
5. Create Maven Profiles for SNAPSHOT deploy and release of versions
6. For releases I'd like to use maven-release-plugin as it automates a lot of tasks.
 1. Creates a tag of the release
 2. Builds on the tag
 3. Updates the versioning numbers

### CODE REVIEW

**Comment by dblock** [comment]
This diff looks suspiciously empty, need help with git?

https://github.com/dblock/log4jna/pull/15/files?w=1

**Comment by claudiow** [comment]
Wrong branch. I should be merging maven-conversion

**Comment by claudiow** [comment]
Closi

**Comment by claudiow** [comment]
Closing to reopen with proper branch

**Pull request closed without merging**
