### PR TITLE
Fix CI(Testing)

### PR DESCRIPTION
**Pull request by yokra9**
* Install latest secure-file from GitHub Release, not NuGet.
* Modify variable secret to specify valid value.

Encrypted value won't be decrypted at PR across fork repo, so that I created this PR directly.

### CODE REVIEW

**Comment by yokra9** [comment]
Sorry, I couldn't resolve the problem about signing artifacts. I couldn't find a way that maven-gpg-plugin uses gpg command included msys. May anyone help?

```
"%SECURE_FILE_CMD%" %SECURE_FILE_DEC% %PUB_KEY_FILE_ENC% %SECURE_FILE_SEC% %secret% -out %PUB_KEY_FILE_GPG%
WARNING: You are using a hard-coded salt value! Please re-encrypt your data so a randomized salt can be generated (which you will also need to store).
"%SECURE_FILE_CMD%" %SECURE_FILE_DEC% %SEC_KEY_FILE_ENC% %SECURE_FILE_SEC% %secret% -out %SEC_KEY_FILE_GPG%
WARNING: You are using a hard-coded salt value! Please re-encrypt your data so a randomized salt can be generated (which you will also need to store).
gpg --import %PUB_KEY_FILE_GPG%
gpg: keybox '/home/appveyor/.gnupg/pubring.kbx' created
gpg: /home/appveyor/.gnupg/trustdb.gpg: trustdb created
gpg: key 2A1D76C91D042AE2: public key "Log4JNA Team <db@dblock.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg --batch --passphrase %secret% --import %SEC_KEY_FILE_GPG%
gpg: key 2A1D76C91D042AE2: "Log4JNA Team <db@dblock.org>" not changed
gpg: key 2A1D76C91D042AE2: secret key imported
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg:       secret keys read: 1
gpg:   secret keys imported: 1
```

```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ log4jna ---
gpg: keyblock resource '/c/projects/log4jna-release/C:\Users\appveyor\.gnupg/pubring.kbx': No such file or directory
gpg: skipped "1D042AE2": No secret key
gpg: signing failed: No secret key
```

**Comment by dblock** [comment]
Looks like https://github.com/dblock/log4jna/pull/50 passed CI? Can this be closed?

**Comment by yokra9** [comment]
Please keep this to be opened.

#50 only passed `appveyor.yml`.
 
To release new version on maven central, it need to pass `appveyor-deploy.yml` and `apveyor-mvn-relese.yml`. 

On This PR, I tried to fix these 2 problems, but I couldn’t solve.

**Comment by dblock** [comment]
> I suggest migrating from AppVeyor to GitHub Actions.
> GitHub Actions allows you to use MSVC on Windows Server, and use maven and GPG to sign and deploy.
> 
> When I checked the sample project, I could add the GPG private key and passphrase to the repository configuration and be able to sign it securely. https://github.com/yokra9/log4jna_sample/blob/main/.github/workflows/main.yml https://github.com/yokra9/log4jna_sample/actions/runs/1853174209
> 
> If you'd like, I can close this PR and help you set up GitHub Actions.

Yes, please! That would be amazing.

**Pull request closed without merging**
