### PR TITLE
GPG File signing and assembly (distributable zip) ready

### PR DESCRIPTION
**Pull request by claudiow**
This was a slow week, but I managed to finish a lot of appveyor and project configuration.

- AppVeyor install of file-decrypt to upload encrypted certificates and other files that might conain passwords
- AppVeyor imports GPG keys
- AppVeyor imports mave setting.xm and settings-security.xml
- Assembly project now builds a zip that resembles log4jna-1.3.zip

I added maven settings and security files to the build project. Its seems a good place  for this configuration files that have to be added to appveyor to sign and deploy the SNAPSHOT builds to Sonatype.

We need to talk about signing certificates, for now I'm using a gpg key pair that I created for the project but they contain my name and email, I think that they should contain your name and email.

Before merging check the assembly project on my master and let me know if you like the final file.

### CODE REVIEW

**Comment by dblock** [comment]
This looks good, but the build is failing, I am happy to merge when it's green. There're conflicts to, so rebase it.

LMK what I need to do for GPG keys. To be honest I have very little experience with promoting builds to maven central so explain it to me like a 2 yo :)

**Comment by claudiow** [comment]
I'll do the merge once the build is fixed.

Deploying to Maven central 101:

Maven can deploy to any repository based on the pom configuration using the `<distributionManagement>` section of the POM.

```xml
  <distributionManagement>

   <!-- The site is uploaded to this server -->
    <site>
      <id>sites</id>
      <name>site</name>
     <!-- Upload protocol (ssh) and target server -->
      <url>scp://httpd.cgtca.ca/var/www/sites/log4jna/</url>
    </site>

    <!-- The release builds are uploaded to this server -->
    <repository>
      <id>OSSRH</id>
      <layout>default</layout>
      <name>CGTCA Repo - Nexus Server Releases</name>
      <url>http://repo.cgtca.ca:8081/nexus/content/repositories/releases/</url>
    </repository>

    <!-- The SNAPSHOT builds are uploaded to this server -->
    <snapshotRepository>
      <id>OSSRH</id>
      <layout>default</layout>
      <name>CGTCA Repo - Nexus Server Snapshots</name>
      <url>http://repo.cgtca.ca:8081/nexus/content/repositories/snapshots/</url>
    </snapshotRepository>
  </distributionManagement>
```

Whenever you use the `deploy` goal maven builds the executable jar and deploys it to a repository based on the version number. If the version ends with -SNAPSHOT it deploys to the snapshot repository if it ends on a number it deploys to the releases repository.

The credentials for the servers are saved in the users `settings.xml` located in the `%userprofile%\.m2` directory see the ones in [my fork build/Maven](https://github.com/claudiow/log4jna/tree/master/build/Maven)

For shared projects it is recommended that the passwords are encrypted see [maven guide to encription](https://maven.apache.org/guides/mini/guide-encryption.html)

Now releasing to central is no different except for the requirements and that it is done using a 2 steps process.

First we deploy to Sonatype's release repository and create a staging repository, then we promoto that repository to Maven centrals

The requirements are:

1. You must create an account in Sonatype using their Jira server see [this](https://issues.sonatype.org/browse/OSSRH-23287) for the process I followed for `org.dblock` and [this ](http://central.sonatype.org/pages/apache-maven.html)for more information
2. The sources and javadoc jar are mandatory
3. All files must be signed with at least gpg and the signing public key must be provided in .asc format

I hope that this is clear enough.

**Comment by claudiow** [comment]
There is another maven plug-in that I favour for deploying releases see the [maven-release-plugin](http://maven.apache.org/maven-release/maven-release-plugin/) documentation.

I like that this plugin takes care of versioning and creating a tag for each release. therefore there is always a recovery point for any release no mater of the state of `master`.

If we use this from the CI server there will be no need of instructions to collaborators for releases, you just trigger a manual build in AppVeyor. More on this when I'm done and I understand the process as right now I'm advancing very slowly by trial and error. AppVeyor is dedicated to .NET and I'm doing a lot of tweaking in the yaml file to get everything working.

In my commercial life I found this very helpful. Having a maintenance stream for old versions of projects that have some deprecated functionality while the main development continues It is very useful when  the JDK or dependencies become incompatible like Java 1.4 and 5 or Log4J 1 and 2.

**Comment by claudiow** [comment]
The build and conflicts are fixed.

You may find that this brakes your CI build, this is because of the encrypted password used to decrypt the certificate files.

AppVeyor generates a key per account to encrypt variables. If this is the case I'll send you the password in an encrypted personal mail.

**Comment by claudiow** [comment]
This is wrong we should me merging from my master it is synced with the branch and your master.

I will open an new pull request from there. You can close this one once you read the maven instructions you requested

**Comment by dblock** [comment]
I merged #18, closing.

**Pull request closed without merging**
