### PR TITLE
fix CI (change mvn download URI and build image)

### PR DESCRIPTION
**Pull request by yokra9**
There seem to be some issues with the appveyor configuration file, which I assume is the cause of the problems we are experiencing with CI. 

* Fixed maven download link.
* Specify VS2015 w/ Windows Sever 2012 as the build environment

refs:
* https://github.com/dblock/log4jna/issues/45#issuecomment-929279143
* <https://ci.appveyor.com/project/yokra9/log4jna/builds/40954030>

Thanks!

### CODE REVIEW

**Comment by dblock** [comment]
Thank you!

**Comment by dblock** [comment]
Do you want to come help out make a 2.0 release off what we have here on master, @yokra9?

**Comment by yokra9** [comment]
Sure! I'll fix #40 and #42 ( I can’t make sense of #41).  furthermore, I’ll create PR to bump JNA to 5.9. Finally, I’ll help out make a 2.0 release off .

**Comment by dblock** [comment]
Invited you to this repo, see https://github.com/dblock/log4jna/invitations

We have pretty thorough docs on releasing to maven and such, but I haven't done it in a long time, you lmk if you need anything like access and how I can grant that, https://github.com/dblock/log4jna/blob/master/MavenRelease.md.

**Comment by dblock** [comment]
cc: @claudiow who did this last time around

**Comment by yokra9** [comment]
Thank you for inviting.  I'll work on it little by little.
BTW, [v2.0 seems to be already released on maven central](https://mvnrepository.com/artifact/org.dblock.log4jna/log4jna-api/2.0), so should I release v2.1?

**Comment by dblock** [comment]
> Thank you for inviting. I'll work on it little by little. BTW, [v2.0 seems to be already released on maven central](https://mvnrepository.com/artifact/org.dblock.log4jna/log4jna-api/2.0), so should I release v2.1?

Oh looks like CHANGELOG and other things weren't updated! Please do.

**Pull request merged**
