### PR TITLE
Fix build, corrected AppVeyor badge.

### PR DESCRIPTION
**Pull request by dblock**
Iterating until the build is green.

### CODE REVIEW

**Comment by claudiow** [comment]
Success the build is green on dblock/master with my secret at [https://ci.appveyor.com/project/claudiow/log4jna-7o8kf](https://ci.appveyor.com/project/claudiow/log4jna-7o8kf)

You can change the secret in master if you want to see it green on your appveyor environment.

Until I finish writing the maven site and documentation, and testing the deployment to Central I still need my own build environment pointing to my internal servers. 

Maven central does not allow delete of published releases and I don't want to have garbage there

**Comment by dblock** [comment]
That's what I thought this PR would do, but it's failing in a strange way: https://ci.appveyor.com/project/dblock/log4jna/build/2.0.38

```
Error: Secret passphrase is missing.
USAGE:
Encrypting file:
```

What am I missing?

**Comment by claudiow** [comment]
That the appveyor.yml file still is using my encryption of secret.

```yaml

  secret:
    secure: Z851+sNOAoEP/lr/3hGjRjC+SlaO19wPqPAYGZFEgfY=

  #secret:
  #  secure: 2jB/P5OINYqlYP3vH2SkPolt/GG6eP8WpL2XOXszfwY=
```
Here is an idea, for the time been why don't we use the badge pointing to the build of dblock/master on my appveyor account, that way it will reflect the state of the build and not the usage of the encrypted password. 

We are overwriting this with each PR as what I'm testing is the appveyor build not code changes.

**Comment by claudiow** [comment]
I see the new error, let me check the source in github

**Comment by dblock** [comment]
From https://www.appveyor.com/docs/how-to/secure-files: "Note that file won't be decrypted on Pull Request builds as secure variables are not set during PR build." Bleh.

**Comment by claudiow** [comment]
Daniel you made the change in a branch but the build is in master, merge to see the fix taking effect.

Or create a new build that checks out ci-fix

**Comment by claudiow** [comment]
Yup, this ahs been the problem from the begining

**Comment by claudiow** [comment]
That is why I create a build per branch in my appveyor environment I test the build and then I request a PR

**Comment by dblock** [comment]
This whole thing is going to continue creating problems. I want people to be able to contribute to this project and rely on CI, and right now we cannot. If we cannot have "green" pull requests, how can we know that the change didn't break anything?

What are the changes we need to do to make pull requests just build code and run tests? I don't see why that requires any secrets.

**Comment by dblock** [comment]
@claudiow I created a gitter room, want to pair up and chat there?

[Gitter](https://gitter.im/dblock/log4jna?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by dblock** [comment]
Closing in favor of https://github.com/dblock/log4jna/pull/36.

**Pull request closed without merging**
