### PR TITLE
Fix yml squashed

### PR DESCRIPTION
**Pull request by claudiow**
I repeated the whole process and I still have a lot of commits, but it is not 200+

### CODE REVIEW

**Comment by dblock** [comment]
Maybe you needed to rewind way further first than 100 commits... lets just not worry about it, I can merge squashed via github. 

Now I see a bunch of extra files here though, `log4jna-api`, some `.bak` files. Can you please clean up and look at the diff here and make sure it's the diff you want me to merge?

**Comment by dblock** [comment]
You could try squashing your commits within the branch, see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html maybe.

**Comment by claudiow** [comment]
Cleaned up, and the files check.

I added the renaming of the packages here

**Comment by dblock** [comment]
I've merged this. Try to make clean PRs moving forward with 1 single commit, use `--amend`.

**Comment by dblock** [comment]
@claudiow Before you make more changes do make sure your master is 100% in sync with upstream. The best way is always:

```
git checkout master
git reset HEAD~200 # rewind 200 commits
git pull upstream master
git push origin master # might need -f if it was out of sync
```

Then, follow CONTRIBUTING.md, make topic branches off master and PR from them. Every PR should have 1 (or not many more) commits and only commits relevant to that PR.

**Comment by claudiow** [comment]
Something is not right here:
```
claudiow@Karl MINGW64 ~/git/log4jna (fix-yml-squashed)
$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

claudiow@Karl MINGW64 ~/git/log4jna (master)
$ git reset HEAD~200
fatal: ambiguous argument 'HEAD~200': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

claudiow@Karl MINGW64 ~/git/log4jna (master)
$ git reset HEAD~150
fatal: ambiguous argument 'HEAD~150': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

claudiow@Karl MINGW64 ~/git/log4jna (master)
$ git reset HEAD~125
fatal: ambiguous argument 'HEAD~125': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by claudiow** [comment]
Success from my master header `This branch is even with dblock:master. `

**Comment by dblock** [comment]
That ~125 wasn't working cause there're only 49 commits total on log4jna :) So that number is too big. Glad you're now in sync.

I also suggest you cleanup all your stale branches locally and on Github. So:

```
git branch
```

Then delete any branch you don't need with `git branch -D <name>`.

Check remote branches with `git branch -r`, those on Github. Then delete them with `git push origin :<name>`. 

I also use a [git-delete-merged](https://github.com/dblock/dotfiles/blob/master/bash/bin/git-delete-merged) shortcut to delete anything that has been merged and that's in sync, so my typical workflow goes like this:

```
git checkout master
git pull upstream master
git-delete-merged

git checkout -b new-feature-branch
.... work
git add .
git commit ....
git push origin new-feature-branch
.... work some more
git add .
git commit --amend or git commit depending on whether I want to change the previous commit or add one
git push origin new-feature-branch -f # -f when I did amend
... make a pull request, get it merged
(repeat)
```

**Comment by dblock** [comment]
Also, check http://code.dblock.org/2015/08/31/getting-out-of-your-first-git-mess.html, could be helpful to understand what was going on ^^^.

**Pull request merged**
