### PR TITLE
This is the correct pull request

### PR DESCRIPTION
**Pull request by claudiow**
All what we discussed on #17 applies here

### CODE REVIEW

**Comment by dblock** [comment]
Merged.

**Comment by dblock** [comment]
What do I need to configure to fix master after this?
https://ci.appveyor.com/project/dblock/log4jna/build/2.0.4

**Comment by claudiow** [comment]
This is the encryption problem that I mentioned to you.in #17. The encrypted password to decode the certificates is wrong.

I will send you the password in a private mail and you have to encrypt it in AppVeyor using the Ecrypt data tool. The tool is in the menu that deploys when you click in the user profile down arrow (Top Right of the Page)

Replace the generate key in the appveyor.yml file.

```yaml
version: 2.0.{build}
os: Windows Server 2012
branches:
  only:
  - master

environment:
  MAVEN_HOME: C:\maven\apache-maven-3.3.9
  PATH: C:\maven\apache-maven-3.3.9\bin;$(JAVA_HOME)\bin;$(PATH)
  MAVEN_OPTS: -Xmx4g
  JAVA_OPTS: -Xmx4g
  M2: $(USERPROFILE)\.m2
  SETTINGS: $(APPVEYOR_BUILD_FOLDER)\build\Maven\settings.xml
  SETTINGS_SEC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\settings-security.xml
  M2_SETTINGS: $(USERPROFILE)\.m2\settings.xml
  M2_SETTINGS_SEC: $(USERPROFILE)\.m2\settings-security.xml
  GNUPG_HOME: $(USERPROFILE)\.gnupg
  PUB_KEY_FILE_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\pubring.gpg.asc.enc
  SEC_KEY_FILE_ENC: $(APPVEYOR_BUILD_FOLDER)\build\Maven\secring.gpg.asc.enc
  PUB_KEY_FILE_GPG: $(APPVEYOR_BUILD_FOLDER)\build\Maven\pubring.gpg.asc
  SEC_KEY_FILE_GPG: $(APPVEYOR_BUILD_FOLDER)\build\Maven\secring.gpg.asc
  SECURE_FILE_DIR: C:\secure-file

  secret:
    # Replace this with your generated key
    secure: Z851+sNOAoEP/lr/3hGjRjC+SlaO19wPqPAYGZFEgfY=

install:
   ....
```

**Comment by claudiow** [comment]
Good day Daniel,


Use this for #18 av3ryd1dicults3cr3t


Claudio Trajtenberg
CTrajtenberg Inc
PH (204) 949-1810
eMail claudio.trajtenberg@cgtca.ca

**Comment by claudiow** [comment]
And this is to complex to keep it. I'm investigating a better way.
I will open a feature request to discuss this going forward.
We can't be sending the password or request every collaborator to crate its own.

**Comment by dblock** [comment]
I've committed the encrypted value in https://github.com/dblock/log4jna/commit/ca911e9ff29493d816997537cc5dd3c4de8d5810. It would be good to find a better solution obviously, but I think we can live with this as long as we properly document it.

**Comment by dblock** [comment]
Build  failed with this:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project log4jna: Unable to decrypt gpg passphrase: org.sonatype.plexus.components.sec.dispatcher.SecDispatcherException: java.io.FileNotFoundException: C:\Users\appveyor\.m2\settings-security.xml (The system cannot find the file specified) -> [Help 1]
```

https://ci.appveyor.com/project/dblock/log4jna/build/2.0.5

**Comment by claudiow** [comment]
There is a typo in appveyor.yml at line 65.

Change  

```yaml
       if (!(Test-Path $env:M2_SETTINGS_SEC)) {
          Copy-Item $env:SETTINGS $M2_SETTINGS_SEC -Verbose
        } elseif((Get-FileHash $env:M2_SETTINGS_SEC).hash -ne (Get-FileHash $env:SETTINGS_SEC).hash) {
          Copy-Item $env:SETTINGS $env:M2_SETTINGS_SEC -Force -Verbose
        } else {
          Write-Host "$env:M2_SETTINGS_SEC up to date"
        }
```
In the Write-Item cmdlet where it says `$env:SETTINGS` it should be `$env:SETTINGS_SEV`

Sorry about that, it seems that I didn't test that condition.

**Comment by dblock** [comment]
It's not a big deal, but can you please PR a fix? We'll have a build double-check.

Also I think https://github.com/dblock/log4jna/blob/master/appveyor-mvn-conversion.yml is redundant?

**Pull request merged**
